# -*- coding: utf-8 -*-
"""Untitled19.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1y8VkywGtB1DU6X8WH_PswzftOaSfFyjR
"""

def radix_sort_MSD_for_strings (array, i):

    # base case (list must already be sorted)
    if len(array) <= 1:
        return array

    # divide (first by length, then by order of the first character)
    done_bucket = []
    buckets = [ [] for x in range(64,100) ] # ASCII TABLE A-Z is from 64 to 90

    for s in array:
        if i >= len(s):
            done_bucket.append(s)
        else:
            buckets[ ord(s[i]) - ord('a') ].append(s)

    # ***********conquer (recursively sort buckets)***********
    buckets = [ radix_sort_MSD_for_strings (b, i + 1) for b in buckets ]
    return done_bucket + [ b for blist in buckets for b in blist ]
def main():
    array_of_strings = ['User','Admin','docx', 'text', 'test']       # ASCII TABLE A-Z is from 64 to 90 if you want to    #change it  to lowercase letter Also change the bucket list's range                
                                                         
    print('before radix_sort:')
    print (array_of_strings)
    array_of_strings = radix_sort_MSD_for_strings (array_of_strings, 0)
    print('after radix_sort')
    print (array_of_strings)
main()

#Генератор

import random
random.seed(8) # 0, 5, 8, ...

# символы, из которых будут составляться слова
symbols = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'

def generation_random_string(len1, seed=None):
    if seed is not None:
        random.seed(seed)
        
    string = ''.join(random.choice(symbols) for i in range(len1))
    
    
    return string

generation_random_string(5)